//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewIIDIprogram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityId { get; set; }
        public int StepId { get; set; }
        public string ActivityName { get; set; }
        public string DoneBy { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string PhotoPath { get; set; }
        public string VideoPath { get; set; }
        public string ActivityNotes { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> CompleteTime { get; set; }
        public string AuxiName { get; set; }
    
        public virtual ProgramStep ProgramStep { get; set; }
    }
}
