//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewIIDIprogram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiomatricFingerprintMapping
    {
        public int Id { get; set; }
        public string BiomatricLogId { get; set; }
        public Nullable<int> Hand { get; set; }
        public Nullable<int> FingerType { get; set; }
        public Nullable<int> PositionOfFingerprint { get; set; }
        public byte[] FingerprintImage { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public string FingerprintImagePath { get; set; }
    }
}
