//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewIIDIprogram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInformation
    {
        public int ClientId { get; set; }
        public string Biomatric { get; set; }
        public string ReferenceID { get; set; }
        public string FristName { get; set; }
        public string LastName { get; set; }
        public string ParentsName { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> Credits { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Handedness { get; set; }
        public string Ethnicity { get; set; }
        public string BloodGroup { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Referances { get; set; }
        public string Adress { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<int> Zipcode { get; set; }
        public Nullable<int> EvalutionType { get; set; }
        public string Languages { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ClientPhoto { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<int> Capturedby { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<int> Deletedby { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ReferalCode { get; set; }
        public string RegisterdBy { get; set; }
        public string VerificationToken { get; set; }
        public string IsEmailVerified { get; set; }
        public Nullable<System.DateTime> AppoimentDate { get; set; }
        public string PinCode { get; set; }
        public Nullable<bool> ShowDetails { get; set; }
        public Nullable<System.Guid> UserProfileID { get; set; }
        public string Userid { get; set; }
    }
}
