//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewIIDIprogram.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class imiMappingDbEntities : DbContext
    {
        public imiMappingDbEntities()
            : base("name=imiMappingDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<GetInTouch> GetInTouches { get; set; }
        public virtual DbSet<LoginUser> LoginUsers { get; set; }
        public virtual DbSet<MasterStep> MasterSteps { get; set; }
        public virtual DbSet<NavigatorItem> NavigatorItems { get; set; }
        public virtual DbSet<ProgramFeature> ProgramFeatures { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<ProgramStatu> ProgramStatus { get; set; }
        public virtual DbSet<ProgramStepProgress> ProgramStepProgresses { get; set; }
        public virtual DbSet<ProgramStep> ProgramSteps { get; set; }
        public virtual DbSet<ClientInformation> ClientInformations { get; set; }
        public virtual DbSet<BiomatricFingerprintMapping> BiomatricFingerprintMappings { get; set; }
        public virtual DbSet<ClientProgramMapping> ClientProgramMappings { get; set; }
        public virtual DbSet<MasterRole> MasterRoles { get; set; }
    }
}
