//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewIIDIprogram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramStep()
        {
            this.Activities = new HashSet<Activity>();
            this.ProgramStatus = new HashSet<ProgramStatu>();
        }
    
        public int StepId { get; set; }
        public string StepTitle { get; set; }
        public string StepDescription { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> MasterStepId { get; set; }
        public Nullable<bool> IsAIGenerated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual MasterStep MasterStep { get; set; }
        public virtual Program Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramStatu> ProgramStatus { get; set; }
    }
}
