//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewIIDIprogram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.ProgramStatus = new HashSet<ProgramStatu>();
            this.ProgramSteps = new HashSet<ProgramStep>();
        }
    
        public int ProgramId { get; set; }
        public string ProgramName { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsReportUploaded { get; set; }
        public string ReportFilePath { get; set; }
        public Nullable<bool> IsReportUpdated { get; set; }
        public Nullable<double> PrimaryPercent { get; set; }
        public Nullable<double> SecondaryPercent { get; set; }
        public Nullable<double> TertiaryPercent { get; set; }
        public Nullable<double> LeftBrain { get; set; }
        public Nullable<double> RightBrain { get; set; }
        public Nullable<double> LoopPercent { get; set; }
        public Nullable<double> ArchPercent { get; set; }
        public Nullable<double> IntrapersonalPercent { get; set; }
        public Nullable<double> LogicPercent { get; set; }
        public Nullable<double> FineMotorPercent { get; set; }
        public Nullable<double> SpeechPercent { get; set; }
        public Nullable<double> ObservationPercent { get; set; }
        public Nullable<double> InterpersonalPercent { get; set; }
        public Nullable<double> ImaginationPercent { get; set; }
        public Nullable<double> GrossMotorPercent { get; set; }
        public Nullable<double> EmotionPercent { get; set; }
        public Nullable<double> BeautyPercent { get; set; }
        public string ReportRawText { get; set; }
        public Nullable<double> WhorlPercent { get; set; }
        public Nullable<double> AxPercent { get; set; }
    
        public virtual LoginUser LoginUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramStatu> ProgramStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramStep> ProgramSteps { get; set; }
    }
}
