//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewIIDIprogram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramStatu
    {
        public int ProgramStatusId { get; set; }
        public System.DateTime ClassDate { get; set; }
        public System.TimeSpan ClassTime { get; set; }
        public string Navigator { get; set; }
        public string ClassDescription { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public int UserId { get; set; }
        public int ProgramId { get; set; }
        public int StepId { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual ProgramStep ProgramStep { get; set; }
    }
}
